IntegratedAppraisalControl/Controllers/InventoryController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using IntegratedAppraisalControl.Models;
using IntegratedAppraisalControl.Models.DTO;
using IntegratedAppraisalControl.Business;
using System.Security.Claims;
using IntegratedAppraisalControl.Classes;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Hosting;

namespace IntegratedAppraisalControl.Controllers
{
    [Authorize]
    public class InventoryController : BaseController
    {
        private readonly IClientBusiness _ClientBusiness;
        private readonly IUserBusiness _UserBusiness;
        private readonly IBuildingBusiness _BuildingBusiness;
        private readonly ICommonBusiness _CommonBusiness;
        private readonly IInventoryBusiness _inventoryBusiness;
        private IHostingEnvironment _hostingEnvironment;
        public InventoryController(
            IClientBusiness clientBusiness,
            IUserBusiness userBusiness,
            IBuildingBusiness buildingBusiness,
            ICommonBusiness commonBusiness,
            IInventoryBusiness inventoryBusiness,
            IHostingEnvironment environment
            )
        {
            _ClientBusiness = clientBusiness;
            _UserBusiness = userBusiness;
            _BuildingBusiness = buildingBusiness;
            _CommonBusiness = commonBusiness;
            _inventoryBusiness = inventoryBusiness;
            _hostingEnvironment = environment;
        }

        public async Task<IActionResult> Index()
        {
            InventorySearchCriteria criteria = new
            InventorySearchCriteria()
            {
                InventoryId = 0,
                ClientID = BaseClientId,
                IsSuperAdmin = BaseSuperAdmin,
                IsClientAdmin = BaseClientAdmin
            };

            ViewBag.listBuildings = await _BuildingBusiness.GetBuildingListDDlBySearchCriteriaAsync(
               new BuildingSearchCriteriaModel()
               {
                   ClientID = BaseClientId,
                   IsSuperAdmin = BaseSuperAdmin
               });

            ViewBag.lstAssetClass = await _inventoryBusiness.GetAssetClassListDDL(criteria);
            ViewBag.lstRooms = await _inventoryBusiness.GetRoomsListDDL(criteria);
            ViewBag.lstDepartments = await _inventoryBusiness.GetDepartmentListDDL(criteria);
            return View(new TblInventoryDTO());
        }

        [HttpGet]
        public async Task<JsonResult> InventoryList()
        {
            var InventoryList = await _inventoryBusiness.GetInventoryList(
                new InventorySearchCriteria()
                {
                    ClientID = BaseClientId,
                    IsSuperAdmin = BaseSuperAdmin,
                    IsClientAdmin = BaseClientAdmin
                });


            return Json(new
            {
                data =
                InventoryList.Select(data =>
                    new
                    {
                        Tag = data.Tag,
                        BuildingCode = data.BuildingCode,
                        Floor = data.Floor,
                        RoomCode = data.RoomCode,
                        DepartmentCode = data.DepartmentCode,
                        AssetClassCode = data.AssetClassCode,
                        Qty = data.Qty,
                        Descr = data.Descr,
                        Pono = data.Pono,
                        Crn = data.Crn,
                        SoundValue = data.SoundValue,
                        Cost = data.Cost,
                        Month = data.Month,
                        Year = data.Year,
                        SerNo = data.SerNo,
                        Mfg = data.Mfg,
                        Model = data.Model,
                        InventoryId = data.InventoryId,
                    })
            });
        }

        [HttpGet]
        public async Task<JsonResult> GetRoomListByBuildingId(int BuildingId)
        {
            List<TblRoomsDTO> lstRooms = await _inventoryBusiness.GetRoomsListDDL(new InventorySearchCriteria()
            {
                ClientID = BaseClientId,
                IsSuperAdmin = BaseSuperAdmin,
                IsClientAdmin = BaseClientAdmin,
                BuildingId = BuildingId
            });

            return Json(new
            {
                data = lstRooms.Select(data =>
                    new
                    {
                        Value = data.RoomId,
                        Text = data.RoomDescription,
                    })
            });
        }

        public async Task<IActionResult> Edit(int Id)
        {
            InventorySearchCriteria criteria = new
            InventorySearchCriteria()
            {
                InventoryId = Id,
                ClientID = BaseClientId,
                IsSuperAdmin = BaseSuperAdmin,
                IsClientAdmin = BaseClientAdmin
            };

            InventoryViewModel inventoryViewModel = new InventoryViewModel();
            inventoryViewModel.Inventory = await _inventoryBusiness.GetInventory(criteria);
            if (inventoryViewModel.Inventory == null)
            {
                return View("AccessDenied");
            }

            inventoryViewModel.listBuildings = await _BuildingBusiness.GetBuildingListDDlBySearchCriteriaAsync(
                new BuildingSearchCriteriaModel()
                {
                    ClientID = BaseClientId,
                    IsSuperAdmin = BaseSuperAdmin
                });

            criteria.BuildingId = Convert.ToInt32(inventoryViewModel.Inventory.BuildingId);
            inventoryViewModel.lstAssetClass = await _inventoryBusiness.GetAssetClassListDDL(criteria);
            inventoryViewModel.lstRooms = await _inventoryBusiness.GetRoomsListDDL(criteria);
            inventoryViewModel.lstDepartments = await _inventoryBusiness.GetDepartmentListDDL(criteria);

            inventoryViewModel.lstChangesTypeDTO = await _CommonBusiness.GetChangeTypeSearchCriteriaAsync(new ChangeTypeCriteriaModel() { Active = true, IsSuperAdmin = BaseSuperAdmin });

            return View(inventoryViewModel);
        }
        [HttpPost]
        public async Task<JsonResult> Edit(InventoryViewModel inventoryViewModel, IFormFile file)
        {
            bool Status = false;
            string Message = "", Data = "";
            InventorySearchCriteria criteria = new
            InventorySearchCriteria()
            {
                InventoryId = inventoryViewModel.Inventory.InventoryId,
                ClientID = BaseClientId,
                IsSuperAdmin = BaseSuperAdmin,
                IsClientAdmin = BaseClientAdmin,
                TagNo = inventoryViewModel.Inventory.Tag
            };


            try
            {
                if (Convert.ToBoolean(inventoryViewModel.IsDuplicate))
                {
                    criteria.InventoryId = 0;
                }

                if (!string.IsNullOrEmpty(criteria.TagNo) && await _inventoryBusiness.CheckInventoryTagExistance(criteria))
                {
                    Status = false;
                    Message = "Please check tag no. Tag no is duplicate.";
                }
                else
                {
                    criteria.InventoryId = inventoryViewModel.Inventory.InventoryId;
                    TblInventoryDTO invOld = await _inventoryBusiness.GetInventory(criteria);

                    if (invOld != null)
                    {
                        invOld.ImageFileName = inventoryViewModel.Inventory.ImageFileName;
                        //if (invOld.ImageFileName != null || invOld.ImageFileName != "")
                        //{
                        if (file != null && file.Length > 0)
                        {
                            var uploads = Path.Combine(_hostingEnvironment.WebRootPath, "uploads");
                            string FileName = System.IO.Path.GetFileNameWithoutExtension(file.FileName) + DateTime.Now.ToFileTime() + System.IO.Path.GetExtension(file.FileName);
                            var filePath = Path.Combine(uploads, FileName);

                            if (!System.IO.Directory.Exists(uploads))
                            {
                                System.IO.Directory.CreateDirectory(uploads);
                            }

                            if (System.IO.File.Exists(filePath))
                                System.IO.File.Delete(filePath);

                            using (var fileStream = new FileStream(filePath, FileMode.Create))
                            {
                                await file.CopyToAsync(fileStream);
                            }
                            invOld.ImageFileName = FileName;
                        }
                        //}
                        //else
                        //{
                        //    invOld.ImageFileName = "";
                        //}

                        if (inventoryViewModel.IsDuplicate)
                        {
                            invOld.InventoryId = 0;
                            Message = "Record duplicated. You can find that recoerd in list.";
                        }
                        else
                        {
                            Message = "Record updated.";
                        }

                        if (Convert.ToBoolean(inventoryViewModel.Inventory.MarkForDeletion))
                        {
                            Message = "Record mark as deleted.";
                        }


                        invOld.Tag = inventoryViewModel.Inventory.Tag;
                        invOld.BuildingId = inventoryViewModel.Inventory.BuildingId;
                        invOld.RoomId = inventoryViewModel.Inventory.RoomId;

IntegratedAppraisalControl/Views/Inventory/_AddEditInventoryMaintenance.cshtml
@model IntegratedAppraisalControl.Models.InventoryViewModel
@{ }

<form class="" action="@Url.Action("AddChange","Inventory")" id="frnChangesMaintanance">
    <div class="form-group">
        <label for="ddlChangeType">Change Type</label>
        <input type="hidden" id="ChangeType" />
        @Html.DropDownListFor(m => m.objtblInventoryMaintenanceDTO.ChangeTypeId, new SelectList(Model.lstChangesTypeDTO, "ChangeTypeId", "ChangeType"), "", new { placeholder = "changeType", @class = "form-control required required2" })
    </div>
    <div class="form-group">
        <label for="txtDescription">Description</label>
        @Html.TextAreaFor(m => m.objtblInventoryMaintenanceDTO.Description, new { @class = "form-control required required2", @maxlength = "50", @placeholder = "Description", @style = "height: 214px;" })
        @Html.HiddenFor(m => m.Inventory.InventoryId)
        @Html.HiddenFor(m => m.objtblInventoryMaintenanceDTO.InventoryId)
        @Html.HiddenFor(m => m.objtblInventoryMaintenanceDTO.InventoryMaintenanceId)
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <label class="" for="txtMonthAcquired">Month Acquired</label>
                @Html.TextBoxFor(m => m.objtblInventoryMaintenanceDTO.MonthAcq, new { @class = "form-control required required2", @maxlength = "2",@max=12, @min = 1, @number = true, @placeholder = "Month Acquired" })
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label class="" for="txtYearAcquired">Year Acquired</label>
                @Html.TextBoxFor(m => m.objtblInventoryMaintenanceDTO.YearAcq, new { @class = "form-control required required2", @maxlength = "4",@max=2099, @min = 1901, @number =true, @placeholder = "Year Acquiredd" })
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label class="">Cost</label>
                @Html.TextBoxFor(m => m.objtblInventoryMaintenanceDTO.Cost, new { @class = "form-control required required2", @maxlength = "10", @placeholder = "Cost" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="modal-footer">
            <button type="button" class="btn btn-primary" id="AddChange">
                Save
            </button>
            <button type="button" class="btn btn-default"
                    data-dismiss="modal">
                Close
            </button>
        </div>
    </div>
</form>