IntegratedAppraisalControl/Controllers/LocationController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using IntegratedAppraisalControl.Models;
using IntegratedAppraisalControl.Models.DTO;
using IntegratedAppraisalControl.Business;
using System.Security.Claims;
using IntegratedAppraisalControl.Classes;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Hosting;

namespace IntegratedAppraisalControl.Controllers
{
    [Authorize]
    public class LocationController : BaseController
    {
        private readonly ILocationBusiness _locationBusiness;

        public LocationController(
            ILocationBusiness locationBusiness
            )
        {
            _locationBusiness = locationBusiness;
        }

        public async Task<IActionResult> Index()
        {
            LocationSearchCriteria criteria = new
            LocationSearchCriteria()
            {
                LocationId = 0,
                ClientID = BaseClientId,
                IsSuperAdmin = BaseSuperAdmin,
                IsClientAdmin = BaseClientAdmin
            };

            ViewBag.lstAnnualDepreciation = await _locationBusiness.GetAnnualDepreciationListDDL(criteria);
            ViewBag.lstFirstYearDepreciationList = await _locationBusiness.GetFirstYearDepreciationListDDL(criteria);

            return View(new TblClientsDTO());
        }

        [HttpGet]
        public async Task<JsonResult> LocationList()
        {
            var LocationList = await _locationBusiness.GetLocationList(
                new LocationSearchCriteria()
                {
                    ClientID = BaseClientId,
                    IsSuperAdmin = BaseSuperAdmin,
                    IsClientAdmin = BaseClientAdmin,
                    BaseUserId = BaseUserId
                });


            return Json(new
            {
                data =
                LocationList.Select(data =>
                    new
                    {
                        Name = data.ClientName,
                        FileNo = data.FileNo,
                        Addrees1 = data.Address1,
                        Address2 = data.Address2,
                        City = data.City,
                        State = data.State,
                        ZipCode = data.ZipCode,
                        PointOfContact = data.PointOfContact,
                        Telephone = data.Telephone,
                        ReportYear = data.ReportYear,
                        AccountingYear = data.AccountingYear,
                        AquisitionCostCutOff = data.AquisitionCostCutOff,
                        LastUpdated = data.LastUpdated,
                        AnnualDepreciationId = data.AnnualDepreciationId,
                        FirstYearDepreciationD = data.FirstYearDepreciationD,
                        Active = Convert.ToBoolean(data.Active) ? "Active" : "Inactive",
                        ClientId = data.ClientId,
                        FirstYearDepreciationText = data.FirstYearDepreciationText,
                        AnnualDepreciationText = data.AnnualDepreciationText
                    })
            });
        }

        public async Task<IActionResult> _AddEdit(int Id)
        {
            TblClientsDTO tblClients = new TblClientsDTO();

            LocationSearchCriteria criteria = new
            LocationSearchCriteria()
            {
                LocationId = Id,
                ClientID = BaseClientId,
                IsSuperAdmin = BaseSuperAdmin,
                IsClientAdmin = BaseClientAdmin
            };

            if (Id != 0)
            {
                tblClients = await _locationBusiness.GetClients(criteria);
            }

            if (tblClients == null)
            {
                tblClients = new TblClientsDTO();
            }

            tblClients.Active = tblClients.Active.HasValue ? tblClients.Active.Value : false;

            ViewBag.lstAnnualDepreciation = await _locationBusiness.GetAnnualDepreciationListDDL(criteria);
            ViewBag.lstFirstYearDepreciationList = await _locationBusiness.GetFirstYearDepreciationListDDL(criteria);

            return PartialView(tblClients);

        }

        public async Task<IActionResult> Edit(int Id)
        {
            TblClientsDTO tblClients = new TblClientsDTO();

            LocationSearchCriteria criteria = new
            LocationSearchCriteria()
            {
                LocationId = Id,
                ClientID = BaseClientId,
                IsSuperAdmin = BaseSuperAdmin,
                IsClientAdmin = BaseClientAdmin
            };

            if (Id != 0)
            {
                tblClients = await _locationBusiness.GetClients(criteria);
            }

            if (tblClients == null)
            {
                tblClients = new TblClientsDTO();
            }

            tblClients.Active = tblClients.Active.HasValue ? tblClients.Active.Value : false;

            ViewBag.lstAnnualDepreciation = await _locationBusiness.GetAnnualDepreciationListDDL(criteria);
            ViewBag.lstFirstYearDepreciationList = await _locationBusiness.GetFirstYearDepreciationListDDL(criteria);

            return View(tblClients);
        }

        [HttpPost]
        public async Task<JsonResult> Add(TblClientsDTO client)
        {
            bool Status = false;
            string Message = "Record updated.", Data = "";

            LocationSearchCriteria criteria = new
            LocationSearchCriteria()
            {
                LocationId = 0,
                ClientID = 0,
                IsSuperAdmin = BaseSuperAdmin,
                IsClientAdmin = BaseClientAdmin,
            };

            try
            {
                //if (await _locationBusiness.CheckInventoryTagExistance(criteria))
                //{
                //    Status = false;
                //    Message = "Please check tag no. Tag no is duplicate.";
                //}
                //else
                //{
                if (!BaseReadOnly)
                {
                    //client.ClientId = BaseClientId;
                    client.LastUpdated = System.DateTime.Now.ToString("dd/mm/yyyy");
                    client.ClientStatusId = Convert.ToInt32(client.Active);

                    if(client.ClientId > 0)
                    {
                        Message = "Record updated successfully.";
                    }
                    else
                    {
                        Message = "Record inserted successfully.";
                    }

                    client = await _locationBusiness.AddUpdateClients(client);
                    Status = true;
                }
                else
                {
                    Status = false;
                    Message = "You have readonly permission.";
                }
                //}
            }
            catch (Exception ex)
            {
                Status = false;
                Message = "There is some issue, Please try again after sometime.";
                Data = ex.Message;
            }

            return Json(new
            {
                Status = Status,
                Message = Message,
                Data = Data
            });
        }

        

    }
}

IntegratedAppraisalControl/Views/Location/Index.cshtml
@model IntegratedAppraisalControl.Models.DTO.TblClientsDTO
@{
    ViewBag.Title = "Location List";
}

<div class="panel-group main" id="accordion">
    <div class="panel panel-primary">
        <div class="panel-heading">
            @if (!(ViewBag.BaseReadOnly))
            {
            <div class="btn-group pull-right">
                @*<a href="#" data-toggle="modal" data-target="#modalAddLoaction" class="btn btn-default btn-sm">&nbsp; Add</a>*@
                <button class="btn btn-default btn-sm" id="btnAdd">Add</button>
            </div>
            }
            <h4 class="panel-title">
                @ViewBag.Title
            </h4>
        </div>
        <div id="Locationsections" class="panel-collapse collapse in">
            <div class="panel-body">

                <div class="row">
                    <div class="col-md-12">
                        <div class="table-responsive" style="overflow-x:scroll">
                            <table id="tblLocationList">
                                <thead>
                                    <tr>
                                        <th>
                                            Name
                                        </th>
                                        <th>
                                            File No
                                        </th>
                                        <th>
                                            Address1
                                        </th>
                                        <th>
                                            Address2
                                        </th>
                                        <th>
                                            City
                                        </th>
                                        <th>
                                            State
                                        </th>
                                        <th>
                                            Zip Code
                                        </th>
                                        <th>
                                            Point Of Contact
                                        </th>
                                        <th>
                                            Telephone
                                        </th>
                                        <th>
                                            Report Year
                                        </th>
                                        <th>
                                            Accounting Year
                                        </th>
                                        <th>
                                            Aquisition Cost Cutoff
                                        </th>
                                        <th>
                                            Last Updated
                                        </th>
                                        <th>
                                            Annual Depreciation
                                        </th>
                                        <th>
                                            First year Depreciation
                                        </th>
                                        <th>
                                            Status
                                        </th>
                                        <th>
                                            Edit
                                        </th>
                                    </tr>
                                </thead>
                                <tbody></tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@if (!(ViewBag.BaseReadOnly))
{
    <div class="modal fade" id="modalAddLoaction" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-lg" style="width: 1140px;">
            <div class="modal-content">
                <!-- Modal Header -->
                <div class="modal-header">
                    <button type="button" class="close"
                            data-dismiss="modal">
                        <span aria-hidden="true">&times;</span>
                        <span class="sr-only">Close</span>
                    </button>
                    <h4 class="modal-title">
                        Add/Edit Location
                    </h4>
                </div>
                <!-- Modal Body -->
                <div class="modal-body" id="popupAdd">
                </div>
                <!-- Modal Footer -->
            </div>
        </div>
    </div>
}


@section Scripts{
    <script type="text/javascript">

        function LoadTaleData() {
            $.ajax({
                url: '@Url.Action("LocationList", "Location")',
                type: 'GET',
                dataType: "json",
                success: function (response) {

                         var table = $('#tblLocationList').DataTable({
                                data: response.data,
                                 columns: [
                                     { data: "Name" },
                                     { data: "FileNo" },
                                     { data: "Addrees1" },
                                     { data: "Address2" },
                                     { data: "City" },
                                     { data: "State" },
                                     { data: "ZipCode" },
                                     { data: "PointOfContact" },
                                     { data: "Telephone" },
                                     { data: "ReportYear" },
                                     { data: "AccountingYear" },
                                     { data: "AquisitionCostCutOff" },
                                     { data: "LastUpdated" },
                                     { data: "AnnualDepreciationText" },
                                     { data: "FirstYearDepreciationText" },
                                     { data: "Active" },
                                     { data: "ClientId" }
                                    ],
                                destroy: true,
                                "aLengthMenu": [
                                    [5, 10, 15, 20, -1],
                                    [5, 10, 15, 20, "All"]
                             ],
                                 dom: 'Bfrtip',
                                buttons: [
                                    {
                                        extend: 'csvHtml5',
                                        title: 'Loaction csv',
                                        className:'btn btn-primary',
                                        exportOptions: {
                                            columns: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
                                        }
                                    },
                                    {
                                        extend: 'excelHtml5',
                                        title: 'Loaction excel',
                                        className: 'btn btn-primary',
                                        exportOptions: {
                                            columns: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
                                        }
                                    }
                             ],
                             "aoColumnDefs": [
                                 {
                                     "aTargets": [16],
                                     "visible": false
                                 }
                             ],

                             "iDisplayLength": @ViewBag.BasePageSize,
                             "language": {
                                 "emptyTable": "No data available in table"
                             },
                             "drawCallback": function (settings) {
                                 var api = this.api();
                                 $("#tblLocationList tbody tr").dblclick(function () {
                                     window.location.href = '@Url.Action("Edit", "Location")' + '?Id=' + table.row(this).data().ClientId;
                                 });
                             }
                         })
                    //}
                },
                error: function (req, status, error) {
                    alert('There is some issue with server. Please try again later.');
                }
        });
        }

        function loadPopup1(Id) {

            $.ajax({
                url: '@Url.Action("_AddEdit", "Location")',
                type: 'GET',
                data: {
                    Id: Id
                },
                success: function (html) {
                    $('#popupAdd').html(html);

                    if ($('#Active').val() == 'True') {
                        $("input[name=optrole][value='Active']").prop("checked", true);
                    }
                    else {
                        $("input[name=optrole][value='Inactive']").prop("checked", true);
                    }

                    if (!($('#modalAddLoaction').is(':visible')))
                    {
                        $('#modalAddLoaction').modal('show');
                    }

                    submitForm();
                },
                error: function () {
                    alert('There is some issue, Please try again after some time.')
                }
            });
        }

        function submitForm() {
            fnFormvalidate("frmLocation");
            $('#frmLocation').submit(function (e) {
                e.preventDefault(); // avoid to execute the actual submit of the form.
                if (!$("#frmLocation").valid()) {
                    return;
                }


                $(this).ajaxSubmit({
                    success: function (responseText, statusText, xhr, $form) {
                        alert(responseText.Message);
                        console.log(responseText.Data);
                        if (responseText.Status) {
                            $('#frmLocation').resetForm();
                            //$('.imgpreview').attr('src', $('.imgpreview').data('oldimage'));
                            LoadTaleData();
                        }
                    }
                });
                return false;
            });
        }

        $(document).ready(function () {
            
            $('#btnAdd').click(function () {
                loadPopup1(0);
            });

            $(document).on('change', 'input[type=radio][name=optrole]', function () {
                $('#Active').val(false);
                $('#' + $(this).val()).val(true);
            });

            LoadTaleData();
        });
    </script>
}

IntegratedAppraisalControl/Views/Location/_AddEdit.cshtml
@model IntegratedAppraisalControl.Models.DTO.TblClientsDTO
@{

    if(Model.ClientId == 0)
    {
        Model.NextRoomNumber = 9000;
        Model.NextDepartmentNumber = 9000;
    }
}


@using (Html.BeginForm("Add", "Location", FormMethod.Post, new { @class = "form-horizontal", @id = "frmLocation" }))
{
    <div class="panel-body">
        <div class="row">
            <div class="col-md-5">
                <div class="form-group col-md-12">
                    <label class="col-lg-3 control-label">Name:</label>
                    <div class="col-lg-9">
                        @Html.TextBoxFor(m => m.ClientName, new { @class = "form-control required required2", @maxlength = "50", @placeholder = "Name" })
                        @Html.HiddenFor(m => m.ClientId)
                    </div>
                    @*<label class="col-lg-2 control-label">System #:</label>*@
                    @*<label class="col-lg-2 control-label">@Model.ClientId</label>*@
                </div>
                <div class="form-group col-md-12">
                    <label class="col-lg-3 control-label">Address1:</label>
                    <div class="col-lg-9">
                        @Html.TextBoxFor(m => m.Address1, new { placeholder = "Address 1", @class = "select2 required required2 form-control", @maxlength = "50" })
                    </div>
                </div>
                <div class="form-group col-md-12">
                    <label class="col-lg-3 control-label">Address2:</label>
                    <div class="col-lg-9">
                        @Html.TextBoxFor(m => m.Address2, new { placeholder = "Address 2", @maxlength = "50", @class = "select2 form-control" })
                    </div>
                </div>
                <div class="form-group col-md-12">
                    <label class="col-lg-3 control-label">City:</label>
                    <div class="col-lg-9">
                        @Html.TextBoxFor(m => m.City, new { placeholder = "City", @maxlength = "50", @class = "select2 required required2 form-control" })
                    </div>
                </div>
                <div class="form-group col-md-12">
                    <label class="col-lg-3 control-label">State:</label>
                    <div class="col-lg-9">
                        @Html.TextBoxFor(m => m.State, new { placeholder = "State", @maxlength = "5", @class = "select2 required required2 form-control" })
                    </div>
                </div>
                <div class="form-group col-md-12">
                    <label class="col-lg-3 control-label">ZipCode:</label>
                    <div class="col-lg-9">
                        @Html.TextBoxFor(m => m.ZipCode, new { @class = "form-control required required2", @maxlength = "10", @placeholder = "ZipCode" })
                    </div>
                </div>
                <div class="form-group col-md-12">
                    <label class="col-lg-3 control-label">Point Of Contact:</label>
                    <div class="col-lg-9">
                        @Html.TextBoxFor(m => m.PointOfContact, new { @class = "form-control  required required2", @maxlength = "100", @placeholder = "Point Of Contact" })
                    </div>
                </div>
                <div class="form-group col-md-12">
                    <label class="col-lg-3 control-label">Telephone:</label>
                    <div class="col-lg-9">
                        @Html.TextBoxFor(m => m.Telephone, new { @class = "form-control  required required2", @maxlength = "25", @placeholder = "Telephone" })
                    </div>
                </div>

                <div class="form-group col-md-12">
                    <label class="col-lg-3 control-label">Report Year:</label>
                    <div class="col-lg-9">
                        @Html.TextBoxFor(m => m.ReportYear, new { @class = "form-control  required required2", @maxlength = "4",@type="number", @placeholder = "Report Year" })
                    </div>
                </div>

                <div class="form-group col-md-12">
                    <label class="col-lg-3 control-label">Accounting Year:</label>
                    <div class="col-lg-9">
                        @Html.TextBoxFor(m => m.AccountingYear, new { @class = "form-control  required required2", @maxlength = "4",@type ="number", @placeholder = "Accounting Year" })
                    </div>
                </div>

                <div class="form-group col-md-12">
                    <label class="col-lg-3 control-label">Cost CutOff:</label>
                    <div class="col-lg-9">
                        @Html.TextBoxFor(m => m.AquisitionCostCutOff, new { @class = "form-control  required required2", @maxlength = "10",@type="number", @placeholder = "Cost CutOff" })
                    </div>
                </div>

                <div class="form-group col-md-12">
                    <label class="col-lg-3 control-label">Annual Depreciation:</label>
                    <div class="col-lg-9">
                        @Html.DropDownListFor(m => m.AnnualDepreciationId, new SelectList(ViewBag.lstAnnualDepreciation, "AnnualDepreciationId", "AnnualDepreciationText"), "", new { placeholder = "Annual Depreciation", @class = "select2 required required2 form-control" })
                        @*@Html.TextBoxFor(m => m.AnnualDepreciationId, new { @class = "form-control", @placeholder = "Annual Depreciation" })*@
                    </div>
                </div>

                <div class="form-group col-md-12">
                    <label class="col-lg-3 control-label">First Year Depreciation:</label>
                    <div class="col-lg-9">
                        @Html.DropDownListFor(m => m.FirstYearDepreciationD, new SelectList(ViewBag.lstFirstYearDepreciationList, "FirstYearDepreciationId", "FirstYearDepreciationText"), "", new { placeholder = "First Year Depreciation", @class = "select2 required required2 form-control" })
                        @*@Html.TextBoxFor(m => m.FirstYearDepreciationD, new { @class = "form-control", @placeholder = "First Year Depreciation" })*@
                    </div>
                </div>
            </div>
            <div class="col-md-5">
                <div class="form-group col-md-12">
                    <label class="col-lg-3 control-label">Sdf1 Label:</label>
                    <div class="col-lg-9">
                        @Html.TextBoxFor(m => m.Sdf1label, new { @class = "form-control", @maxlength = "50", @placeholder = "Sdf1 Label" })
                    </div>
                </div>
                <div class="form-group col-md-12">
                    <label class="col-lg-3 control-label">Sdf2 Label:</label>
                    <div class="col-lg-9">
                        @Html.TextBoxFor(m => m.Sdf2label, new { @class = "form-control", @maxlength = "50", @placeholder = "Sdf2 Label" })
                    </div>
                </div>
                <div class="form-group col-md-12">
                    <label class="col-lg-3 control-label">Sdf3 Label:</label>
                    <div class="col-lg-9">
                        @Html.TextBoxFor(m => m.Sdf3label, new { @class = "form-control", @maxlength = "50", @placeholder = "Sdf3 Label" })
                    </div>
                </div>
                <div class="form-group col-md-12">
                    <label class="col-lg-3 control-label">Sdf4 Label:</label>
                    <div class="col-lg-9">
                        @Html.TextBoxFor(m => m.Sdf4label, new { @class = "form-control", @maxlength = "50", @placeholder = "Sdf4 Label" })
                    </div>
                </div>
                <div class="form-group col-md-12">
                    <label class="col-lg-3 control-label">Status:</label>
                    <div class="col-lg-9">
                        @Html.HiddenFor(m => m.Active)
                        <label class="checkbox-container">
                            Active
                            <input type="radio" name="optrole" class="clsRole" value="Active">
                            <span class="checkmark"></span>
                        </label>
                        <label class="checkbox-container">
                            Inactive
                            <input type="radio" name="optrole" class="clsRole" value="Inactive">
                            <span class="checkmark"></span>
                        </label>

                        @*@Html.TextBoxFor(m => m.ClientStatusId, new { @class = "form-control", @placeholder = "Status" })*@
                    </div>
                </div>
                <div class="form-group col-md-12">
                    <label class="col-lg-3 control-label">File No:</label>
                    <div class="col-lg-9">
                        @Html.TextBoxFor(m => m.FileNo, new { @class = "form-control required required2", @maxlength = "10", @placeholder = "File No" })
                    </div>
                </div>
                <div class="form-group col-md-12">
                    <label class="col-lg-3 control-label">Appraisal Date</label>
                    <div class="col-lg-9">
                        @Html.TextBoxFor(m => m.AppraisalDate, new { @class = "form-control required required2", @maxlength = "10", @placeholder = "Appraisal Date" })
                    </div>
                </div>
                <div class="form-group col-md-12">
                    <label class="col-lg-3 control-label">Updated To:</label>
                    <div class="col-lg-9">
                        @Html.TextBoxFor(m => m.UpdatedTo, new { @class = "form-control required required2", @maxlength = "10", @placeholder = "UpdatedTo" })
                    </div>
                </div>

                <div class="form-group col-md-12">
                    <label class="col-lg-3 control-label">Account Data As Of:</label>
                    <div class="col-lg-9">
                        @Html.TextBoxFor(m => m.AccountDataAsOf, new { @class = "form-control required required2", @maxlength = "10", @placeholder = "AccountDataAsOf" })
                    </div>
                </div>

                <div class="form-group col-md-12">
                    <div class="col-lg-12">
                        @Html.CheckBoxFor(m => m.Accounting)Accounting &nbsp;&nbsp;&nbsp;
                        @Html.CheckBoxFor(m => m.Insurance)Insurance &nbsp;&nbsp;&nbsp;
                        @Html.CheckBoxFor(m => m.Fmv)Fmv
                    </div>
                </div>

                <div class="form-group col-md-12">
                    <label class="col-lg-3 control-label">Next Room Number:</label>
                    <div class="col-lg-9">
                        @Html.TextBoxFor(m => m.NextRoomNumber, new { @class = "form-control required required2", @digits = true, @placeholder = "Next Room Number" })
                    </div>
                </div>
                <div class="form-group col-md-12">
                    <label class="col-lg-3 control-label">Next Department Number:</label>
                    <div class="col-lg-9">
                        @Html.TextBoxFor(m => m.NextDepartmentNumber, new { @class = "form-control required required2", @digits = true, @placeholder = "Next Department Number" })
                    </div>
                </div>

            </div>

        </div>
    </div>

    <div class="panel-footer">
        @if (!(ViewBag.BaseReadOnly))
        {
            <div class="modal-footer">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" id="btnSave" class="btn btn-primary" value="Save" />
                    @*<input type="button" id="btnUndo" class="btn btn-primary" value="Undo" />
                        <input type="submit" id="btnSaveDupl" class="btn btn-primary" value="Save / Duplicate" />

                        @if (!Convert.ToBoolean(Model.MarkForDeletion))
                        {
                            <input type="submit" id="btnDelete" class="btn btn-primary" value="Delete" />
                        }
                        else
                        {
                            <input type="button" class="btn btn-primary" value="Already mark for delete" disabled />
                        }*@
                    <a href="@Url.Action("Index","Location")" class="btn btn-primary">Exit</a>
                </div>
            </div>
        }
    </div>
}