IntegratedAppraisalControl/Controllers/RoomsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using IntegratedAppraisalControl.Models;
using IntegratedAppraisalControl.Models.DTO;
using IntegratedAppraisalControl.Business;
using Microsoft.AspNetCore.Hosting;

namespace IntegratedAppraisalControl.Controllers
{
    [Authorize]
    public class RoomsController : BaseController
    {
        private readonly IRoomsBusiness _roomsBusiness;
        private readonly IClientBusiness _ClientBusiness;
        private IHostingEnvironment _hostingEnvironment;
        private readonly IBuildingBusiness _BuildingBusiness;
        public RoomsController(
            IRoomsBusiness roomsBusiness,
            IBuildingBusiness buildingBusiness,
            IClientBusiness clientBusiness,
            IHostingEnvironment environment
        )
        {
            _roomsBusiness = roomsBusiness;
            _BuildingBusiness = buildingBusiness;
            _hostingEnvironment = environment;
            _ClientBusiness = clientBusiness;

        }

        public async Task<IActionResult> Index()
        {
            return View(new TblRoomsDTO());
        }

        [HttpGet]
        public async Task<JsonResult> RoomList()
        {
            RoomsearchCriteria criteria = new
            RoomsearchCriteria()
            {
                ClientID = BaseClientId,
                IsSuperAdmin = BaseSuperAdmin,
                IsClientAdmin = BaseClientAdmin
            };
            var RoomList = await _roomsBusiness.GetRoomsList(criteria);

            return Json(new
            {
                data =
                RoomList.Select(data =>
                    new
                    {
                        BuildingCode = data.BuildingCode,
                        RoomCode = data.RoomCode,
                        RoomDescription = data.RoomDescription,
                        MarkForDeletion = data.MarkForDeletion.HasValue ? data.MarkForDeletion.Value : false,
                        RoomId = data.RoomId
                    })
            });
        }

        [HttpGet]
        public async Task<ActionResult> _Room(int RoomId)
        {
            TblRoomsDTO tblRooms = new TblRoomsDTO();
            if (RoomId != 0)
            {
                RoomsearchCriteria criteria = new
               RoomsearchCriteria()
                {
                    ClientID = BaseClientId,
                    IsSuperAdmin = BaseSuperAdmin,
                    IsClientAdmin = BaseClientAdmin,
                    RoomId = RoomId
                };
                tblRooms = await _roomsBusiness.GetRooms(criteria);
            }

            ViewBag.listBuildings = await _BuildingBusiness.GetBuildingListBySearchCriteriaAsync(
              new BuildingSearchCriteriaModel()
              {
                  ClientID = BaseClientId,
                  IsSuperAdmin = BaseSuperAdmin
              });

            if (tblRooms == null)
            {
                tblRooms = new TblRoomsDTO();
            }

            if(tblRooms.RoomId == 0)
            {
                TblClientsDTO tblClientsDTO =  await _ClientBusiness.GeClientDetails(new ClientSearchCriteriaModel { ClientId = BaseClientId });
                if(tblClientsDTO.NextRoomNumber > 0)
                {
                    tblRooms.RoomCode = Convert.ToString(tblClientsDTO.NextRoomNumber);
                }
                else
                {
                    tblRooms.RoomCode = "9000";
                }
            }
            return PartialView(tblRooms);
        }
        [HttpPost]
        public async Task<JsonResult> AddUpdate(TblRoomsDTO tblRooms, bool IsDuplicate)
        {
            bool Status = false;
            string Message = "", Data = "";
            try
            {
                RoomsearchCriteria criteria = new
                    RoomsearchCriteria()
                {
                    ClientID = BaseClientId,
                    IsSuperAdmin = BaseSuperAdmin,
                    IsClientAdmin = BaseClientAdmin,
                    RoomId = tblRooms.RoomId,
                    RoomCode = tblRooms.RoomCode,
                    BuildingId = Convert.ToInt32(tblRooms.BuildingId)
                };

                if (Convert.ToBoolean(IsDuplicate))
                {
                    criteria.RoomId = 0;
                }

                if (await _roomsBusiness.CheckRoomsCodeExistance(criteria))
                {
                    Status = false;
                    Message = "Please check Room code. Room code is duplicate.";
                }
                else
                {
                    if (tblRooms.RoomId > 0)
                    {
                        criteria.RoomId = tblRooms.RoomId;
                        var tblRoomsOld = await _roomsBusiness.GetRooms(criteria);
                        if (IsDuplicate)
                        {
                            tblRoomsOld.RoomId = 0;
                        }
                        tblRoomsOld.ClientId = BaseClientId;
                        tblRoomsOld.RoomCode = tblRooms.RoomCode;
                        tblRoomsOld.RoomDescription = tblRooms.RoomDescription;
                        tblRoomsOld.MarkForDeletion = tblRooms.MarkForDeletion;


                        tblRoomsOld = await _roomsBusiness.AddUpdateRooms(tblRoomsOld);

                        if (IsDuplicate)
                        {
                            Message = "Record duplicated successfully. You will find it on listing.";
                        }
                        else
                        {
                            Message = "Record updated successfully.";
                        }

                        if (Convert.ToBoolean(tblRooms.MarkForDeletion))
                        {
                            Message = "Record marked as deleted.";
                        }
                    }
                    else
                    {
                        Message = "Record added successfully.";
                        tblRooms.ClientId = BaseClientId;
                        tblRooms.Deleted = false;
                        tblRooms.MarkForDeletion = false;

                        tblRooms = await _roomsBusiness.AddUpdateRooms(tblRooms);
                    }


                    Status = true;
                }
            }
            catch (Exception ex)
            {
                Status = false;
                Data = ex.Message;
            }

            return Json(new
            {
                Status = Status,
                Message = Message,
                Data = Data
            });
        }
    }
}

IntegratedAppraisalControl/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IntegratedAppraisalControl.Business;
using IntegratedAppraisalControl.Models;
using IntegratedAppraisalControl.Models.DTO;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace IntegratedAppraisalControl.Controllers
{
    [Authorize]
    public class UsersController : BaseController
    {
        private readonly IUserBusiness _UserBusiness;
        private readonly IClientBusiness _ClientBusiness;
        //private readonly IUserBusiness _UserBusiness;
        //private readonly IBuildingBusiness _BuildingBusiness;
        public UsersController(IUserBusiness userBusiness, IClientBusiness clientBusiness)
        {
            _UserBusiness = userBusiness;
            _ClientBusiness = clientBusiness;
        }

        public async Task<IActionResult> Index()
        {
            return View(new TblUsersDTO());
        }

        [HttpGet]
        public async Task<JsonResult> UserList()
        {
            UserSearchCriteria criteria = new
            UserSearchCriteria()
            {
                ClientID = BaseClientId,
                IsSuperAdmin = BaseSuperAdmin,
                IsClientAdmin = BaseClientAdmin
            };
            var UserList = await _UserBusiness.GetUsersList(criteria);

            return Json(new
            {
                data =
                UserList.Select(data =>
                    new
                    {
                        UserName = data.UserName,
                        FirstName = data.FirstName,
                        LastName = data.LastName,
                        MarkForDeletion = data.Deleted.HasValue ? data.MarkForDeletion.Value : false,
                        UserId = data.UserId
                    })
            });
        }

        [HttpGet]
        public async Task<ActionResult> _User(int UserId)
        {
            TblUsersDTO tblUsers = new TblUsersDTO();
            if (UserId != 0)
            {
                UserSearchCriteria criteria = new UserSearchCriteria()
                {
                    ClientID = BaseClientId,
                    IsSuperAdmin = BaseSuperAdmin,
                    IsClientAdmin = BaseClientAdmin,
                    UserId = UserId
                };
                tblUsers = await _UserBusiness.GetUsers(criteria);
            }

            if (tblUsers == null)
            {
                tblUsers = new TblUsersDTO();
            }

            tblUsers.ReadOnly = tblUsers.ReadOnly.HasValue ? tblUsers.ReadOnly.Value : false;
            tblUsers.ClientAdmin = tblUsers.ClientAdmin.HasValue ? tblUsers.ClientAdmin.Value : false;
            tblUsers.SuperAdmin = tblUsers.SuperAdmin.HasValue ? tblUsers.SuperAdmin.Value : false;
            List<TblUsersClientsDTO> ListUsersClientsDTO = await _UserBusiness.GetClientListByUser(UserId);
            ViewBag.ClientUserList = ListUsersClientsDTO.ToList();

            List<TblClientsDTO> ListClientDDL = await _ClientBusiness.GetClientList();
            ListClientDDL.RemoveAll(m => ListUsersClientsDTO.Select(i => i.ClientId).Contains(m.ClientId));

            foreach(TblClientsDTO cl in ListClientDDL)
            {
                cl.ClientName = cl.FileNo + " - " + cl.ClientName;
            }

            ViewBag.ListClientDDL = ListClientDDL;
            return PartialView(tblUsers);
        }

        [HttpPost]
        public async Task<JsonResult> AddUser(TblUsersDTO tblUsers, bool IsDuplicate)
        {
            bool Status = false;
            string Message = "", Data = "";
            try
            {
                UserSearchCriteria criteria = new
                    UserSearchCriteria()
                {
                    ClientID = BaseClientId,
                    IsSuperAdmin = BaseSuperAdmin,
                    IsClientAdmin = BaseClientAdmin,
                    UserId = tblUsers.UserId,
                    UserName = tblUsers.UserName
                };

                if (Convert.ToBoolean(IsDuplicate))
                {
                    criteria.ClientID = 0;
                }

                bool Duplicate = await _UserBusiness.CheckUserNameExistance(criteria);
                if (tblUsers.UserId == 0 && Duplicate)
                {
                    Status = false;
                    Message = "Please check UserName. UserName is duplicate.";
                }
                else
                {
                    if (tblUsers.UserId > 0)
                    {
                        criteria.UserId = tblUsers.UserId;
                        var tblUsersOld = await _UserBusiness.GetUsers(criteria);
                        if (IsDuplicate)
                        {
                            tblUsersOld.UserId = 0;
                        }

                        tblUsersOld.FirstName = tblUsers.FirstName;
                        tblUsersOld.LastName = tblUsers.LastName;
                        tblUsersOld.ReadOnly = tblUsers.ReadOnly;
                        tblUsersOld.ClientAdmin = tblUsers.ClientAdmin;
                        tblUsersOld.SuperAdmin = tblUsers.SuperAdmin;
                        tblUsersOld.MarkForDeletion = tblUsers.MarkForDeletion;

                        if(!string.IsNullOrEmpty(tblUsers.Password))
                        {
                            tblUsersOld.Password= tblUsers.Password;
                        }

                        tblUsersOld = await _UserBusiness.AddUpdateUsers(tblUsersOld);

                        if (IsDuplicate)
                        {
                            Message = "Record duplicated successfully. You will find it on listing.";
                        }
                        else
                        {
                            Message = "Record updated successfully.";
                        }

                        if (Convert.ToBoolean(tblUsers.MarkForDeletion) && IsDuplicate != true)
                        {
                            Message = "Record marked as deleted.";
                        }
                    }
                    else
                    {
                        Message = "Record added successfully.";
                        tblUsers.ClientId = BaseClientId;
                        tblUsers.Deleted = false;
                        tblUsers.MarkForDeletion = false;
                        tblUsers = await _UserBusiness.AddUpdateUsers(tblUsers);
                    }
                    Status = true;
                }
            }
            catch (Exception ex)
            {
                Status = false;
                Data = ex.Message;
                Message = "There is some issue, Please try again after sometime.";
            }

            return Json(new
            {
                Status = Status,
                Message = Message,
                Data = Data
            });
        }

        [HttpPost]
        public async Task<JsonResult> DeleteUsersClients(int UsersClientsId)
        {
            bool Status = false;
            string Message = "", Data = "";
            try
            {

                if (await _UserBusiness.DeleteUsersClientsMapping(UsersClientsId))
                {
                    Status = true;
                    Message = "Record deleted successfully.";
                }
                else
                {
                    Message = "There is some issue while delete users client. Please contact administrator.";
                }
            }
            catch (Exception ex)
            {
                Status = false;
                Data = ex.Message;
                Message = "There is some issue, Please try again after sometime.";
            }

            return Json(new
            {
                Status = Status,
                Message = Message,
                Data = Data
            });
        }

        [HttpPost]
        public async Task<JsonResult> AddUsersClients(TblUsersClientsDTO tblUsersClientsDTO)
        {
            bool Status = false;
            string Message = "", Data = "";
            try
            {
                tblUsersClientsDTO = await _UserBusiness.AddUpdateUsersClientsMapping(tblUsersClientsDTO);
                Status = true;
                Message = "Record added successfully.";
            }
            catch (Exception ex)
            {
                Status = false;
                Data = ex.Message;
                Message = "There is some issue, Please try again after sometime.";
            }

            return Json(new
            {
                Status = Status,
                Message = Message,
                Data = Data
            });
        }

    }
}

IntegratedAppraisalControl/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

IntegratedAppraisalControl/Views/Home/ClientSelection.cshtml
@model IntegratedAppraisalControl.Models.DTO.TblClientsDTO
@{
    ViewBag.Title = "Location selection";
}
<div class="panel-group main" id="accordion">
    <div class="panel panel-primary">
        <div class="panel-heading" data-toggle="collapse" data-parent="#accordion" href="#buildingmain">
            <h4 class="panel-title">
                Location List
            </h4>
        </div>
        <div id="buildingmain" class="panel-collapse collapse in">

            <div class="panel-body">
                @*<div class="row">
                        <div class="col-md-12 form-group">
                            <button class="btn btn-primary pull-right" data-toggle="modal" data-target="#modalAddBuilding">Add</button>
                        </div>
                    </div>*@
                <div class="row">
                    <div class="col-md-12">
                        <div class="table-responsive">
                            <table id="tblClientList">
                                <thead>
                                    <tr>
                                        <th>
                                            @Html.DisplayNameFor(model => model.ClientId)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.ClientName)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.FileNo)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Address1)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Address2)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.City)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.State)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.ZipCode)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.ReportYear)
                                        </th>
                                    </tr>
                                </thead>
                                <tbody></tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>


        </div>
    </div>
</div>
@section Scripts{
<script type="text/javascript">
           $.ajax({
                url: '@Url.Action("ClientList", "Home")',
                type: 'GET',
                dataType: "json",
                success: function (response) {

                    //if (response.data.length > 0)
                    //{

                        //$('#tblClientList .filters td').each(function () {
                        //    var title = $('#tblClientList thead th').eq($(this).index()).text();
                        //    $(this).html('<input type="text" class="cust-input-sm" placeholder="Search ' + title.trim() + '" />');
                        //});

                        //$('#tblClientList tfoot th').each(function () {
                        //    var title = $(this).text();
                        //    $(this).html('<input type="text" class="cust-input-sm" placeholder="Search ' + title.trim() + '" />');
                        //});

                    var table = $('#tblClientList').DataTable({
                        data: response.data,
                        columns: [
                            { data: "ClientId" },
                            { data: "ClientName" },
                            { data: "FileNo" },
                            { data: "Address1" },
                            { data: "Address2" },
                            { data: "City" },
                            { data: "State" },
                            { data: "ZipCode" },
                            { data: "ReportYear" }
                        ],
                        destroy: true,
                        "aLengthMenu": [
                            [5, 10, 15, 20, -1],
                            [5, 10, 15, 20, "All"]
                        ],
                        "aoColumnDefs": [
                            {
                                "aTargets": [0],
                                "visible": false
                            }
                        ],
                        //"bInfo": false,
                        "bPaginate": true,
                        "iDisplayLength": 10,
                        "drawCallback": function (settings) {
                            var api = this.api();
                            $("#tblClientList tbody tr").dblclick(function () {
                                window.location.href = '@Url.Action("SelectClient", "Home")' + '?ClientId=' + table.row(this).data().ClientId;
                            });
                        }
                    });
                         //    .columns().eq(0).each(function (colIdx) {
                         //    $('input', $('.filters td')[colIdx]).on('keyup change', function () {
                         //        table
                         //            .column(colIdx)
                         //            .search(this.value)
                         //            .draw();
                         //    });
                         //});


                    @*
                        $("#tblClientList tbody tr").unbind("dblclick");

                    $(document).on("dblclick", "#tblClientList tbody tr", function () {
                            window.location.href = '@Url.Action("SelectClient", "Home")' + '?ClientId=' + table.row(this).data().ClientId;
                    });
                    $('#tblClientList tbody tr').dblclick(function () {
                    console.log(table.row(this).data().ClientId);
                        window.location.href = '@Url.Action("SelectClient", "Home")' + '?ClientId=' + table.row(this).data().ClientId;
                    });
                        *@
                },
                error: function (req, status, error) {
                    alert('There is some issue with server. Please try again later.');
                }
            });
</script>
}

IntegratedAppraisalControl/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

IntegratedAppraisalControl/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="white-space">
    <div class="main-catagories">
        <h1>Home</h1>
        <div>
            <div class="col-sm-12">
                <div class="row">
                    <div class="col-xs-6 col-sm-6 col-md-4 col-lg-3 fullDiv">
                        <div class="categoryDiv">
                            <a href="@Url.Action("index","buildings")">
                                <img src="@Url.Content("~/Content/images/building-icon.png")" alt="building icon" />
                            </a>
                            <p>Building</p>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-6 col-md-4 col-lg-3 fullDiv">
                        <div class="categoryDiv">
                            <a href="@Url.Action("index","Inventory")">
                                <img src="@Url.Content("~/Content/images/inventory-icon.png")" alt="inventory icon" />
                            </a>
                            <p>Inventory</p>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-6 col-md-4 col-lg-3 fullDiv">
                        <div class="categoryDiv">
                            <a href="@Url.Action("index","Department")">
                                <img src="@Url.Content("~/Content/images/department-icon.png")" alt="departments icon" />
                            </a>
                            <p>Departments</p>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-6 col-md-4 col-lg-3 fullDiv">
                        <div class="categoryDiv">
                            <a href="@Url.Action("index","Rooms")">
                                <img src="@Url.Content("~/Content/images/rooms-icon.png")" alt="rooms icon" />
                            </a>
                            <p>Rooms</p>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-6 col-md-4 col-lg-3 fullDiv">
                        <div class="categoryDiv">
                            <a href="@Url.Action("Index","Users")">
                                <img src="@Url.Content("~/Content/images/users-icon.png")" alt="users icon" />
                            </a>
                            <p>Users</p>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-6 col-md-4 col-lg-3 fullDiv">
                        <div class="categoryDiv">
                            <a href="@Url.Action("index","Location")">
                                <img src="@Url.Content("~/Content/images/clients-icon.png")" alt="clients icon" />
                            </a>
                            <p>Location</p>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-6 col-md-4 col-lg-3 fullDiv">
                        <div class="categoryDiv">
                            <a href="@Url.Action("index","Reports")">
                                <img src="@Url.Content("~/Content/images/reports-icon.png")" alt="reports icon" />
                            </a>
                            <p>Attachments</p>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-6 col-md-4 col-lg-3 fullDiv">
                        <div class="categoryDiv">
                            <a href="@Url.Action("Index","CertifiedReport")">
                                <img src="@Url.Content("~/Content/images/attachments-icon.png")" alt="attachments icon" />
                            </a>
                            <p>IAC Reports</p>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-6 col-md-4 col-lg-3 fullDiv">
                        <div class="categoryDiv">
                            <a href="@Url.Action("index","transaction")">
                                <img src="@Url.Content("~/Content/images/transections-icon.png")" alt="transections icon" />
                            </a>
                            <p>Transactions</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>